services:
  db:
    image: postgres:15
    container_name: home_security_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fastapi_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  fastapi:
    build: .
    container_name: homesec
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/fastapi_db
      SYNC_DATABASE_URL: postgresql://postgres:postgres@db:5432/fastapi_db
    ports:
      - "8888:8888"
    restart: always

volumes:
  postgres_data: