"""add all_time_access field to access model

Revision ID: 0a234846249d
Revises: 95d5a054c01d
Create Date: 2025-09-20 22:01:19.322318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a234846249d'
down_revision: Union[str, Sequence[str], None] = '95d5a054c01d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access', sa.Column('all_time_access', sa.Boolean(), nullable=False))
    op.alter_column('access', 'from_hour',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('access', 'to_hour',
               existing_type=postgresql.TIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('access', 'to_hour',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('access', 'from_hour',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.drop_column('access', 'all_time_access')
    # ### end Alembic commands ###
