"""no owner needed

Revision ID: 95d5a054c01d
Revises: c648190d8fb0
Create Date: 2025-09-20 20:24:43.357067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95d5a054c01d'
down_revision: Union[str, Sequence[str], None] = 'c648190d8fb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('rooms_owner_id_fkey'), 'rooms', type_='foreignkey')
    op.drop_column('rooms', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('rooms_owner_id_fkey'), 'rooms', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###
