"""add all_time_access field to access mode

Revision ID: de73a3cef360
Revises: 0a234846249d
Create Date: 2025-09-20 22:03:21.931612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de73a3cef360'
down_revision: Union[str, Sequence[str], None] = '0a234846249d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('access', 'all_time_access',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('access', 'all_time_access',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
